### ISSUE TITLE
Feature: Desktop/Laptop/Workstation Planning

### ISSUE THREAD

**Issue by dmgolembiowski** [Neotron-Compute/Neotron-OS#10]
Hey there,

I've been on a operating system kick lately after hearing the Co-Recursive podcast on Serenity OS. Do you think there is any interest in expanding Neotron-OS to provide a super-minimal OS for laptop/desktop users?

**Comment by thejpster** [comment]
I guess you mean x86? So it won't be binary compatible with other Neotron Systems but you could probably write a Neotron BIOS that uses UEFI system calls? Sounds interesting!

**Comment by thejpster** [comment]
Closing this, but do open another issue if there's something you'd like us to change. Or do drop my the Matrix chat room (https://matrix.to/#/#neotron:matrix.org) to discuss this further.
