### ISSUE TITLE
Decide on file format for executables

### ISSUE THREAD

**Issue by thejpster** [Neotron-Compute/Neotron-OS#2]
Options:

* Raw binary
    * Statically linked for 0x2000_0000
    * First word is pointer to start function.
    * Can generate with objcopy
    * This is what Monotron did
* ELF
    * What the EABI Rust target generates
    * Supports relocations?
    * Very complicated and steeped in System-V isms
* MZ DOS Executable
    * Simple
    * Only designed for x86 (e.g. segments)
    * Requires a DOS linker
*  Custom file format
    * Could be made quite simple
    * Can support relocations
    * Requires bespoke linker, or a tool which imports ELF and exports this format

**Comment by IGBC** [comment]
I Like ELF.
I feel we might need relocatable binaries in the future (multiprocessing) and making a custom format seems unnecessarily proprietary.

**Comment by thejpster** [comment]
In which case, we can probably just copy https://github.com/ellbrid/krabs/blob/7becf98e82045f050b41c6c82a957c04699f2284/src/stage_4th/src/loader.rs#L39 ?

**Comment by thejpster** [comment]
Looking at Linux kernel objects and shared objects might also be interesting, as they get relocated as they are loaded into memory.

**Comment by thejpster** [comment]
This is also useful: https://upload.wikimedia.org/wikipedia/commons/e/e4/ELF_Executable_and_Linkable_Format_diagram_by_Ange_Albertini.png

**Comment by thejpster** [comment]
Ok, I really want to write an ELF loader.

**Comment by thejpster** [comment]
Closed in #49
