### ISSUE TITLE
Neotron BIOS link in readme is dead

### ISSUE THREAD

**Issue by Newbytee** [Neotron-Compute/Neotron-OS#9]
Saw your talk through YouTube, so I went here to look at the code. However, I noticed that under the main heading in the readme of this repository, the link to the BIOS necessary to run Netron OS is dead, and it's not immediately obvious to me which repo it is meant to link to given that there are multiple ones named something with BIOS. The dead link in question can be found on this line: https://github.com/Neotron-Compute/Neotron-OS/blob/cd809c3e9826eff3d38e1abf44b16aece77a8798/README.md?plain=1#L3

**Comment by thejpster** [comment]
I wonder what I meant to link to?

Probably Neotron Common BIOS, which describes the API that all BIOSes are supposed to supply. The Neotron Pico BIOS is one particular implementation of that API for one particular board. 

I added an org level readme so hopefully that helps you find your way around.

**Comment by thejpster** [comment]
Pointed at Neotron-Common-BIOS

**Comment by Newbytee** [comment]
Where was this change made? The line I point to in the issue is unchanged.

**Comment by thejpster** [comment]
You point at a commit hash, so that will never change. I made the change in the develop branch.

**Comment by Newbytee** [comment]
Oh, I see. I was looking at the main branch.

**Comment by thejpster** [comment]
The main branch will get updated at the next release.
